In [2]:
import pandas as pd
import numpy as np


In [36]:
user_cols = ['Company','1','X','2']
bets = pd.read_csv("../python_study/data/Odds.Brasil-Mexico.csv",header=None, names=user_cols)

In [37]:
bets.head()

Company     1     X     2
0   10Bet  1.49  4.20  7.75
1   12BET  1.50  3.95  6.70
2  188BET  1.50  4.15  6.80
3   18bet  1.50  4.20  7.75
4   1xBet  1.55  4.20  7.70

In [44]:
#bets.index.name = None
#bets.sum(axis=1)

In [45]:
bets.set_index("Company",inplace=True) #trick to put company as index ...
#bets.index.name = None # just remove company as index name
#bets.reset_index(inplace=True) # ... trick to put it back as column (but we loose the name): need to re-assign (or use inplce)

In [46]:
bets.head()

1     X     2
Company                  
10Bet    1.49  4.20  7.75
12BET    1.50  3.95  6.70
188BET   1.50  4.15  6.80
18bet    1.50  4.20  7.75
1xBet    1.55  4.20  7.70

In [58]:
bets.head()

1     X     2
10Bet   1.49  4.20  7.75
12BET   1.50  3.95  6.70
188BET  1.50  4.15  6.80
18bet   1.50  4.20  7.75
1xBet   1.55  4.20  7.70

In [51]:
# To apply map I need to remove the company column, or make a mask?
bets.apply(lambda x: 1/x).sum(axis=1).head()

Company
10Bet     1.038268
12BET     1.069085
188BET    1.054689
18bet     1.033794
1xBet     1.013127
dtype: float64

In [52]:
# or I can make a smart function that invert only numbers
def invert(x):
    if type(x) is str:
        # just returns it untouched
        return x
    # but, if not, return it multiplied by 100
    elif x!=0:
        return 1/x
    # and leave everything else
    else:
        return x

In [55]:
bets2 = bets.reset_index()
bets2.head()

Company     1     X     2
0   10Bet  1.49  4.20  7.75
1   12BET  1.50  3.95  6.70
2  188BET  1.50  4.15  6.80
3   18bet  1.50  4.20  7.75
4   1xBet  1.55  4.20  7.70

In [66]:
bets_inv = bets2.applymap(invert) #apply map is not function over column or raw, it is a element-wise function, on all elevemts
bets_inv.head()

Company         1         X         2
0   10Bet  0.671141  0.238095  0.129032
1   12BET  0.666667  0.253165  0.149254
2  188BET  0.666667  0.240964  0.147059
3   18bet  0.666667  0.238095  0.129032
4   1xBet  0.645161  0.238095  0.129870

In [103]:
#bets.iloc[:,:].head()

In [356]:
from scipy import stats as stt

In [355]:
# the gain factor (as before)
gf = stt.hmean(bets, axis=1)/3 #this is the harmonic mean, need to devide by 3
gf2 = 3/gf # this is as before, but better to have < 0
gf2.round(4) # set precision

array([4.6723, 4.8108, 4.7462, 4.6521, 4.5592, 4.5773, 4.7382, 4.5592,
       4.6521, 4.7614, 4.6339, 4.6072, 4.5999, 4.591 , 4.6126, 4.6126,
       4.6042, 4.5858, 4.606 , 4.606 , 4.8439, 4.6661, 4.6661, 4.7404,
       4.6723, 4.5957, 4.8108, 4.5999, 4.7679, 4.725 , 4.5773, 4.7679,
       4.8461, 4.6348, 4.5751, 4.6258, 4.6042, 4.606 , 4.6348, 4.5787,
       4.8112, 4.6042, 4.6555, 4.6875, 4.6164, 4.6088, 4.6875, 4.7679,
       4.7382])

In [112]:
bets["GainFactor"] = gf.round(4) #add to DF
bets.head()

1     X     2  GainFactor
Company                              
10Bet    1.49  4.20  7.75      0.9631
12BET    1.50  3.95  6.70      0.9354
188BET   1.50  4.15  6.80      0.9481
18bet    1.50  4.20  7.75      0.9673
1xBet    1.55  4.20  7.70      0.9870

In [117]:
#sort. Best company?
bets.sort_values("GainFactor",ascending=False).head()

1     X     2  GainFactor
Company                                    
1xBet          1.55  4.20  7.70      0.9870
Asianodds      1.52  4.32  8.08      0.9870
Marathonbet    1.53  4.20  8.00      0.9836
Island Casino  1.53  4.20  7.97      0.9831
5Dimes         1.53  4.20  7.97      0.9831

In [134]:
def f(x):
    return pd.Series([x.min(), x.max(), -x.min() + x.max()], index=['min','max','Delta'])

In [148]:
#bets["GainFactor"].apply(f)
bets_d = bets.describe().round(4)
bets_d

1        X        2  GainFactor
count  49.0000  49.0000  49.0000     49.0000
mean    1.5127   4.1400   7.5306      0.9653
std     0.0193   0.1228   0.4828      0.0166
min     1.4500   3.8500   6.5000      0.9286
25%     1.5000   4.0400   7.0000      0.9497
50%     1.5100   4.2000   7.7000      0.9709
75%     1.5300   4.2000   7.9700      0.9774
max     1.5600   4.4000   8.2500      0.9870

In [131]:
bets.describe().round(4).loc['min','1']

1.45

In [139]:
# how to do operation betweens raws
bets_d.loc['min']-bets_d.loc['max']

1            -0.1100
X            -0.5500
2            -1.7500
GainFactor   -0.0584
dtype: float64

In [166]:
# add another line with the Delta
bets_d.loc["DeltaMInMax"] = bets_d.loc['max']-bets_d.loc['min']
bets_d.loc["Delta%"] = (bets_d.loc['max']-bets_d.loc['min'])/bets_d.loc['mean']*100

bets_d.iloc[[1,2,3,-3,-2,-1]]

1          X         2  GainFactor
mean         1.512700   4.140000   7.53060    0.965300
std          0.019300   0.122800   0.48280    0.016600
min          1.450000   3.850000   6.50000    0.928600
max          1.560000   4.400000   8.25000    0.987000
DeltaMInMax  0.110000   0.550000   1.75000    0.058400
Delta%       7.271766  13.285024  23.23852    6.049933

In [161]:
# which is the best? and worse first 3, last 3
bets.sort_values("GainFactor",ascending=False).iloc[[0,1,2,-3,-2,-1]]

1     X     2  GainFactor
Company                                  
1xBet        1.55  4.20  7.70      0.9870
Asianodds    1.52  4.32  8.08      0.9870
Marathonbet  1.53  4.20  8.00      0.9836
SBOBET       1.52  3.85  6.60      0.9353
BetVictor    1.45  4.10  7.00      0.9290
Ladbrokes    1.50  3.90  6.50      0.9286

Let's make now all the combination

In [240]:
N = bets["1"].size

In [254]:
#array with N integer
x = np.arange(N)

In [261]:
# build all triplets of elements in x, 
# there are N^3 triplets, and therefore we need a (N^3,3) array
# I build this column by column (3 columns)
a1 = np.repeat(x,N*N).reshape(N*N*N,1) 
a2 = np.tile(np.repeat(x,N),(N,1)).reshape(N*N*N,1)
a3 = np.vstack([x]*N*N).reshape(N*N*N,1)
#put all togheter
all_comb = np.hstack((a1,a2,a3))
all_comb

array([[ 0,  0,  0],
       [ 0,  0,  1],
       [ 0,  0,  2],
       ...,
       [48, 48, 46],
       [48, 48, 47],
       [48, 48, 48]])

In [274]:
bets2.head()

Company     1     X     2
0   10Bet  1.49  4.20  7.75
1   12BET  1.50  3.95  6.70
2  188BET  1.50  4.15  6.80
3   18bet  1.50  4.20  7.75
4   1xBet  1.55  4.20  7.70

In [339]:
dim = all_comb.shape[0]
dim

117649

In [341]:
pp = np.array([ bets2.iloc[all_comb[n,i],i+1] for n in range(dim) for i in range(3)]).reshape(dim,3)
qq = np.array([ bets2.iloc[all_comb[n,i],0] for n in range(dim) for i in range(3)]).reshape(dim,3)

In [342]:
#pd.DataFrame((pp,qq), columns=["1","X","2","1","X","2"])
df_a = pd.DataFrame(pp, columns=["1","X","2"])
df_b = pd.DataFrame(qq, columns=["Comp_1","Comp_X","Comp_2"])

In [349]:
bets_comb = pd.concat([df_b,df_a], axis=1)
bets_comb.head()

Comp_1 Comp_X  Comp_2     1    X     2
0  10Bet  10Bet   10Bet  1.49  4.2  7.75
1  10Bet  10Bet   12BET  1.49  4.2  6.70
2  10Bet  10Bet  188BET  1.49  4.2  6.80
3  10Bet  10Bet   18bet  1.49  4.2  7.75
4  10Bet  10Bet   1xBet  1.49  4.2  7.70

In [358]:
gf_comb = stt.hmean(pp, axis=1)/3 #this is the harmonic mean, need to devide by 3
bets_comb["GainFactor"] = gf_comb.round(4) #add to DF
bets_comb.head()

Comp_1 Comp_X  Comp_2     1    X     2  GainFactor
0  10Bet  10Bet   10Bet  1.49  4.2  7.75      0.9631
1  10Bet  10Bet   12BET  1.49  4.2  6.70      0.9447
2  10Bet  10Bet  188BET  1.49  4.2  6.80      0.9467
3  10Bet  10Bet   18bet  1.49  4.2  7.75      0.9631
4  10Bet  10Bet   1xBet  1.49  4.2  7.70      0.9624

In [359]:
bets_comb.describe()

1              X              2     GainFactor
count  117649.000000  117649.000000  117649.000000  117649.000000
mean        1.512653       4.140000       7.530612       0.965149
std         0.019142       0.121505       0.477852       0.013104
min         1.450000       3.850000       6.500000       0.906400
25%         1.500000       4.040000       7.000000       0.956300
50%         1.510000       4.200000       7.700000       0.965900
75%         1.530000       4.200000       7.970000       0.974600
max         1.560000       4.400000       8.250000       1.010600

In [360]:
bets_comb.sort_values("GainFactor",ascending=False).head()

Comp_1   Comp_X     Comp_2     1    X     2  GainFactor
60605  Coolbet  BetCity  ScandiBet  1.56  4.4  8.25      1.0106
60600  Coolbet  BetCity  NightRush  1.56  4.4  8.25      1.0106
60580  Coolbet  BetCity    Bethard  1.56  4.4  8.25      1.0106
60571  Coolbet  BetCity  Asianodds  1.56  4.4  8.08      1.0080
60603  Coolbet  BetCity   Pinnacle  1.56  4.4  8.08      1.0080

In [374]:
bets_comb[bets_comb["GainFactor"] > 1.01]

Comp_1   Comp_X     Comp_2     1    X     2  GainFactor
60580  Coolbet  BetCity    Bethard  1.56  4.4  8.25      1.0106
60600  Coolbet  BetCity  NightRush  1.56  4.4  8.25      1.0106
60605  Coolbet  BetCity  ScandiBet  1.56  4.4  8.25      1.0106

In [397]:
idx = bets_comb['GainFactor'].idxmax()
idx

60580

In [429]:
budget = 10000
ff = np.array([1.56, 4.4, 8.25])
bb = 1/ff*1.0106*budget
bb = bb.round(0)
bb

array([6478., 2297., 1225.])

In [427]:
bb.sum()

10000.0

In [428]:
bb*ff

array([10105.68, 10106.8 , 10106.25])